spring.application.name=voip
server.port=8088

# Local port
sip.local.port=5070

# Networks allowed to listen on
sip.local.bind-ip=0.0.0.0

# Reply back IP address
sip.local.contact-ip=127.0.0.1

# Debug trace level, for udp packet and status
sip.stack.trace-level=32

# Callee IP address
sip.server.host=127.0.0.1

# Callee PORT
sip.server.port=5060

sip.message.success=SIP INVITE dispatched successfully
sip.message.error=SIP call failed
sip.message.missing-caller=Missing required parameter: caller
sip.message.missing-callee=Missing required parameter: callee
sip.exception.bind-failed=Failed to bind UDP Listening Point
sip.exception.stack-start-failed=Could not start SIP signaling stack
